using Content.Client.UserInterface.Controls;
using Content.Shared._NF.Shipyard.BUI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._NF.Shipyard.UI;

[GenerateTypedNameReferences]
public sealed partial class BluespaceDrydockConsoleMenu : FancyWindow
{
    public event Action? OnStorePressed;
    public event Action? OnRetrievePressed;

    public BluespaceDrydockConsoleMenu()
    {
        RobustXamlLoader.Load(this);

        StoreButton.OnPressed += _ => OnStorePressed?.Invoke();
        RetrieveButton.OnPressed += _ => OnRetrievePressed?.Invoke();
    }

    public void UpdateState(BluespaceDrydockConsoleInterfaceState state)
    {
        // Update ID card status
        if (state.HasIdCard)
        {
            IdCardStatus.Text = Loc.GetString("bluespace-drydock-console-idcard-present");
        }
        else
        {
            IdCardStatus.Text = Loc.GetString("bluespace-drydock-console-no-idcard");
        }

        // Update active ship display
        if (state.HasActiveDeed && !string.IsNullOrEmpty(state.ActiveShipName))
        {
            ActiveShipName.Text = state.ActiveShipName;
            StoreButton.Disabled = false;
        }
        else
        {
            ActiveShipName.Text = Loc.GetString("bluespace-drydock-console-no-active-ship");
            StoreButton.Disabled = true;
        }

        // Update stored ship display
        if (state.HasStoredShip && !string.IsNullOrEmpty(state.StoredShipName))
        {
            StoredShipName.Text = state.StoredShipName;
            RetrieveButton.Disabled = false;
        }
        else
        {
            StoredShipName.Text = Loc.GetString("bluespace-drydock-console-no-stored-ship");
            RetrieveButton.Disabled = true;
        }

        // Disable store if there's already a stored ship
        if (state.HasStoredShip)
        {
            StoreButton.Disabled = true;
        }

        // Disable retrieve if there's already an active ship
        if (state.HasActiveDeed)
        {
            RetrieveButton.Disabled = true;
        }

        // Disable both if no ID card
        if (!state.HasIdCard)
        {
            StoreButton.Disabled = true;
            RetrieveButton.Disabled = true;
        }
    }
}
